### PR TITLE
update libraries and node to 20

### PR DESCRIPTION
**Pull request by arcticfalcon**

### CODE REVIEW

**Comment by arcticfalcon** [comment]
#tag

**Comment by arcticfalcon** [comment]
#tag

**Review by arlazzari — DISMISSED** [review]

**Comment by arcticfalcon** [comment]
#tag

**Comment by arcticfalcon** [comment]
#tag

**Comment by arcticfalcon** [comment]
#tag

**Comment by arcticfalcon** [comment]
#tag

**Comment by arcticfalcon** [comment]
#tag

**Review by arlazzari — APPROVED** [review]

**Comment by arcticfalcon** [comment]
#tag

**Pull request closed without merging**
